const MenuData =
[
    {
        id:1,
        image: 'Images/Menu/img1.webp',
        title: 'Blissful Bittersweet',
        price:  130.95,
        button: `Add To Cart`,
    },
    {
        id:2,
        image: 'Images/Menu/img2.webp',
        title: 'Sugared Symphonyt',
        price:  172.43,
        button: `Add To Cart`,
    },
    {
        id:3,
        image: 'Images/Menu/img3.webp',
        title: 'Honeyed Havoc',
        price:  250.04,
        button: `Add To Cart`,
    },
    {
        id:4,
        image: 'Images/Menu/img4.webp',
        title: 'Caramel Crush',
        price:  340.12,
        button: `Add To Cart`,
    },
    {
        id:5,
        image: 'Images/Menu/img5.webp',
        title: 'Dark Delight',
        price:  280.79,
        button: `Add To Cart`,
    },
    {
        id:6,
        image: 'Images/Menu/img6.webp',
        title: 'Bitter Chocolate Bliss',
        price:  315.17,
        button: `Add To Cart`,
    },
    {
        id: 7,
        image: 'Images/Product/img1.webp',
        title: 'Morning Bliss Blend',
        price:  180.34,
        stock: `Available Stock: 500`,
        button: 'Add To Cart',
    },
    {
        id: 8,
        image: 'Images/Product/img2.webp',
        title: 'Sunset Serenade Roast',
        price:  241.14,
        stock: `Available Stock: 480`,
        button: 'Add To Cart',
    },
    {
        id: 9,
        image: 'Images/Product/img3.webp',
        title: 'Midnight Magic Brew',
        price:  153.78,
        stock: `Available Stock: 800`,
        button: 'Add To Cart',
    },
    {
        id: 10,
        image: 'Images/Product/img4.webp',
        title: 'Sunrise Symphony Blend',
        price:  350.16,
        stock: `Available Stock: 900`,
        button: 'Add To Cart',
    },
    {
        id: 11,
        image: 'Images/Product/img5.webp',
        title: 'Harmony Harvest Roast',
        price:  235.81,
        stock: `Available Stock: 1210`,
        button: 'Add To Cart',
    },
    {
        id: 12,
        image: 'Images/Product/img6.webp',
        title: 'Dreamy Dawn Delight',
        price:  317.06,
        stock: `Available Stock: 760`,
        button: 'Add To Cart',
    },
];

export default MenuData